### ISSUE TITLE
Yale Door Contact Status

### ISSUE THREAD

**Issue by Mr-Grover** [mattinglis/YaleBinarySensor#4]
Hello,

I been working a rewrite of the yale platform for hassio and have also added in the door contacts. I just wanted to know if the state for your door contacts show as Open/Closed or open/closed ? And also if the door icon in the UI changes based off the state 

Thank you.

**Comment by mattinglis** [comment]
The states are



YALE_DOOR_CONTACT_STATE_CLOSED = "closed"

YALE_DOOR_CONTACT_STATE_OPEN = "open"

YALE_DOOR_CONTACT_STATE_TAMPER = "tamper"

YALE_DOOR_CONTACT_STATE_UNKNOWN = "unknown"

YALE_DOOR_CONTACT_STATE_EMPTY = ""



I have not setup any icons on it, they show as the default tick currently,



Regards





*From:* Mr-Grover ***@***.***>
*Sent:* 13 May 2021 00:19
*To:* mattinglis/YaleBinarySensor ***@***.***>
*Cc:* Subscribed ***@***.***>
*Subject:* [mattinglis/YaleBinarySensor] Yale Door Contact Status (#4)



Hello,

I been working a rewrite of the yale platform for hassio and have also
added in the door contacts. I just wanted to know if the state for your
door contacts show as Open/Closed or open/closed ? And also if the door
icon in the UI changes based off the state

Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mattinglis/YaleBinarySensor/issues/4>, or unsubscribe

**Comment by Mr-Grover** [comment]
Thanks for your reply. That is what I’m seeing in the UI as well even if I use a state map to home assistant Constance like I did with the lock and alarm.  Would be cleaner looking if it was Open/Closed. I’m hoping to submit a PR for my updated yale app soon so thanks again !

**Comment by ZunaidPatel** [comment]
Sorry i am new to home assistant and was wondering how to add the door contacts to my home assistant
